# Window Rules
windowrule = float, class:^(pavucontrol)$
windowrule = float, class:^(blueman-manager)$
windowrule = float, class:^(nm-connection-editor)$
windowrule = float, title:^(File Operation Progress)$
windowrule = float, title:^(Confirm)$
windowrule = float, title:^(Open File)$
windowrule = float, title:^(Save File)$
windowrule = float, title:^(Volume Control)$
windowrule = center, floating:1
windowrule = float, title:^(Picture-in-Picture)$
windowrule = pin, title:^(Picture-in-Picture)$
windowrule = size 480 270, title:^(Picture-in-Picture)$
windowrule = move 100%-490 100%-280, title:^(Picture-in-Picture)$
windowrule = float, title:^(Library)$
windowrule = float, class:^(scratchpad)$
windowrule = size 80% 80%, class:^(scratchpad)$
windowrule = center, class:^(scratchpad)$
windowrule = stayfocused, class:^(wofi)$
windowrule = animation slide, class:^(wofi)$
