windowrule = bordercolor rgb(ff6600), focus:1
windowrule = bordercolor rgb(4a2800), focus:0
windowrule = float, ^(pavucontrol)$
windowrule = float, ^(blueman-manager)$
windowrule = float, ^(nm-connection-editor)$
windowrule = float, title:^(File Operation Progress)$
windowrule = float, title:^(Confirm)$
windowrule = float, title:^(Open File)$
windowrule = float, title:^(Save File)$
windowrule = float, title:^(Volume Control)$
windowrule = center, floating:1
windowrule = float, title:^(Picture-in-Picture)$
windowrule = pin, title:^(Picture-in-Picture)$
windowrule = size 480 270, title:^(Picture-in-Picture)$
windowrule = move 100%-490 100%-280, title:^(Picture-in-Picture)$
windowrule = float, title:^(Library)$
windowrule = float, ^(scratchpad)$
windowrule = size 80% 80%, ^(scratchpad)$
windowrule = center, ^(scratchpad)$
windowrule = stayfocused, ^(wofi)$
windowrule = animation slide, ^(wofi)$
