[search]
placeholder = "Search..."
delay = 0

[list]
height = 300
width = 500
margin_top = 200

[activation_mode]
disabled = false
use_alt = true

[scrollbar]
hide = true

[icons]
hide = false
size = 18

[modules]
applications = true
runner = true
websearch = false
