#!/usr/bin/env bash
# set-theme.sh — Derive a full color palette from one base color and generate
# per-app color files. App configs source/import these files; no hardcoded
# colors live in manually-maintained config files.
#
# Usage:
#   ./scripts/set-theme.sh           # use color from ./theme
#   ./scripts/set-theme.sh '#ff6600' # set new base color and apply

set -euo pipefail

DOTFILES="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
THEME_FILE="$DOTFILES/theme"

# ── 1. Read / update base color ───────────────────────────────────────────────

if [[ -n "${1:-}" ]]; then
    BASE="${1#\#}"
    printf 'base = #%s\n' "$BASE" > "$THEME_FILE"
else
    BASE=$(grep '^base' "$THEME_FILE" | head -1 | sed 's/.*#//' | tr -d '[:space:]')
fi

# ── 2. Derive full palette via Python ─────────────────────────────────────────

eval "$(python3 - "$BASE" <<'PYEOF'
import sys, colorsys

def hex_to_rgb(h):
    h = h.lstrip('#')
    return tuple(int(h[i:i+2], 16) / 255.0 for i in (0, 2, 4))

def rgb_to_hex(r, g, b):
    return '{:02x}{:02x}{:02x}'.format(
        max(0, min(255, round(r * 255))),
        max(0, min(255, round(g * 255))),
        max(0, min(255, round(b * 255))),
    )

def hls_hex(h, l, s):
    r, g, b = colorsys.hls_to_rgb(h, max(0.0, min(1.0, l)), max(0.0, min(1.0, s)))
    return rgb_to_hex(r, g, b)

r, g, b = hex_to_rgb(sys.argv[1])
h, l, s = colorsys.rgb_to_hls(r, g, b)

base         = rgb_to_hex(r, g, b)
bright       = hls_hex(h, min(l * 1.35, 0.92), s)
dim          = hls_hex(h, l * 0.45, s)
surface      = hls_hex(h, l * 0.08, s)
bg           = hls_hex(h, l * 0.10, s)
black        = hls_hex(h, l * 0.04, s)
comment      = hls_hex(h, l * 0.55, s * 0.6)

h_green      = (h + 0.25) % 1.0
h_red        = (h - 0.08) % 1.0
h_yellow     = (h + 0.08) % 1.0
h_blue       = (h + 0.55) % 1.0
h_magenta    = (h + 0.42) % 1.0
h_cyan       = (h + 0.35) % 1.0

green        = hls_hex(h_green, l * 0.70, s * 0.85)
green_bright = hls_hex(h_green, min(l * 0.90, 0.75), s * 0.85)
red          = hls_hex(h_red, l * 0.65, min(s * 1.1, 1.0))
red_bright   = hls_hex(h_red, min(l * 0.85, 0.70), min(s * 1.1, 1.0))
yellow       = hls_hex(h_yellow, l * 0.75, s * 0.95)
yellow_bright= hls_hex(h_yellow, min(l * 0.95, 0.80), s * 0.95)
blue         = hls_hex(h_blue, l * 0.60, s * 0.80)
blue_bright  = hls_hex(h_blue, min(l * 0.80, 0.70), s * 0.80)
magenta      = hls_hex(h_magenta, l * 0.65, s * 0.80)
magenta_bright = hls_hex(h_magenta, min(l * 0.85, 0.75), s * 0.80)
cyan         = hls_hex(h_cyan, l * 0.60, s * 0.75)
cyan_bright  = hls_hex(h_cyan, min(l * 0.80, 0.70), s * 0.75)

error        = red
error_bright = red_bright
warning      = yellow
warning_bright = yellow_bright
success      = green
success_bright = green_bright
info         = blue
info_bright  = blue_bright

l3  = hls_hex(h, l * 0.55, s)
l4  = hls_hex(h, l * 0.75, s)
l5  = hls_hex(h, min(l * 1.50, 0.85), s)
l6  = hls_hex(h, min(l * 1.65, 0.90), s)
l7  = hls_hex(h, min(l * 1.80, 0.95), s)

print(f"BASE='{base}'")
print(f"BRIGHT='{bright}'")
print(f"DIM='{dim}'")
print(f"SURFACE='{surface}'")
print(f"BG='{bg}'")
print(f"BLACK='{black}'")
print(f"COMMENT='{comment}'")
print(f"RED='{red}'")
print(f"RED_BRIGHT='{red_bright}'")
print(f"GREEN='{green}'")
print(f"GREEN_BRIGHT='{green_bright}'")
print(f"YELLOW='{yellow}'")
print(f"YELLOW_BRIGHT='{yellow_bright}'")
print(f"BLUE='{blue}'")
print(f"BLUE_BRIGHT='{blue_bright}'")
print(f"MAGENTA='{magenta}'")
print(f"MAGENTA_BRIGHT='{magenta_bright}'")
print(f"CYAN='{cyan}'")
print(f"CYAN_BRIGHT='{cyan_bright}'")
print(f"ERROR='{error}'")
print(f"ERROR_BRIGHT='{error_bright}'")
print(f"WARNING='{warning}'")
print(f"WARNING_BRIGHT='{warning_bright}'")
print(f"SUCCESS='{success}'")
print(f"SUCCESS_BRIGHT='{success_bright}'")
print(f"INFO='{info}'")
print(f"INFO_BRIGHT='{info_bright}'")

# If you need the P0-P15 palette for Ghostty:
print(f"P0='{black}'")
print(f"P1='{red}'")
print(f"P2='{green}'")
print(f"P3='{yellow}'")
print(f"P4='{blue}'")
print(f"P5='{magenta}'")
print(f"P6='{cyan}'")
print(f"P7='{base}'")
print(f"P8='{dim}'")
print(f"P9='{red_bright}'")
print(f"P10='{green_bright}'")
print(f"P11='{yellow_bright}'")
print(f"P12='{blue_bright}'")
print(f"P13='{magenta_bright}'")
print(f"P14='{cyan_bright}'")
print(f"P15='{bright}'")
PYEOF
)"

echo "Theme: #$BASE"
echo "  bright=#$BRIGHT  dim=#$DIM  surface=#$SURFACE  black=#$BLACK"
echo "  red=#$RED  green=#$GREEN  yellow=#$YELLOW  blue=#$BLUE"

# ── 3. Generate .config/hypr/colors.conf ─────────────────────────────────────

cat > "$DOTFILES/.config/hypr/colors.conf" <<EOF
# Generated by set-theme.sh — do not edit manually.
# Change dotfiles/theme and run scripts/set-theme.sh

\$amber = rgba(${BASE}ff)
\$amber_bright = rgba(${BRIGHT}ff)
\$amber_dim = rgba(${DIM}ff)
\$amber_bg = rgba(${BG}ff)
\$black = rgba(${BLACK}ff)
\$surface = rgba(${SURFACE}ff)
\$red = rgba(${RED}ff)
\$green = rgba(${GREEN}ff)
\$yellow = rgba(${YELLOW}ff)
\$blue = rgba(${BLUE}ff)
EOF

# ── 4. Generate .config/waybar/colors.css ────────────────────────────────────

cat > "$DOTFILES/.config/waybar/colors.css" <<EOF
/* Generated by set-theme.sh — do not edit manually.
   Change dotfiles/theme and run scripts/set-theme.sh */

@define-color base   #$BASE;
@define-color bright #$BRIGHT;
@define-color dim    #$DIM;
@define-color bg     #$BG;
@define-color black  #$BLACK;
EOF

# ── 5. Generate .config/ghostty/colors.conf ──────────────────────────────────

cat > "$DOTFILES/.config/ghostty/colors.conf" <<EOF
# Generated by set-theme.sh — do not edit manually.
# Change dotfiles/theme and run scripts/set-theme.sh

background           = $BLACK
foreground           = $BASE
cursor-color         = $BASE
selection-background = $DIM
selection-foreground = $BASE
palette = 0=#$P0
palette = 1=#$P1
palette = 2=#$P2
palette = 3=#$P3
palette = 4=#$P4
palette = 5=#$P5
palette = 6=#$P6
palette = 7=#$P7
palette = 8=#$P8
palette = 9=#$P9
palette = 10=#$P10
palette = 11=#$P11
palette = 12=#$P12
palette = 13=#$P13
palette = 14=#$P14
palette = 15=#$P15
EOF

# ── 6. Generate .config/mako/config from template ────────────────────────────

sed \
    -e "s/{{BASE}}/#$BASE/g"   \
    -e "s/{{BRIGHT}}/#$BRIGHT/g" \
    -e "s/{{DIM}}/#$DIM/g"     \
    -e "s/{{BG}}/#$BG/g"       \
    -e "s/{{BLACK}}/#$BLACK/g" \
    "$DOTFILES/.config/mako/config.template" > "$DOTFILES/.config/mako/config"

# ── 7. Generate .config/rofi/theme.rasi from template ────────────────────────

sed \
    -e "s/{{BASE}}/#$BASE/g"   \
    -e "s/{{BRIGHT}}/#$BRIGHT/g" \
    -e "s/{{DIM}}/#$DIM/g"     \
    -e "s/{{BG}}/#$BG/g"       \
    -e "s/{{BLACK}}/#$BLACK/g" \
    "$DOTFILES/.config/rofi/theme.rasi.template" > "$DOTFILES/.config/rofi/theme.rasi"

# ── 8. Generate .config/hypr/hyprlock.conf from template ─────────────────────

if [ -f "$DOTFILES/.config/hypr/hyprlock.conf.template" ]; then
    sed \
        -e "s/{{BASE}}/$BASE/g"   \
        -e "s/{{BRIGHT}}/$BRIGHT/g" \
        -e "s/{{DIM}}/$DIM/g"     \
        -e "s/{{BG}}/$BG/g"       \
        -e "s/{{BLACK}}/$BLACK/g" \
        -e "s/{{ERROR}}/$ERROR/g" \
        "$DOTFILES/.config/hypr/hyprlock.conf.template" > "$DOTFILES/.config/hypr/hyprlock.conf"
fi

# ── 9. Generate SDDM theme Main.qml from template ────────────────────────────

SDDM_THEME_DIR="$(dirname "$DOTFILES")/modules/sddm-theme"
if [ -f "$SDDM_THEME_DIR/Main.qml.template" ]; then
    sed \
        -e "s/{{BASE}}/$BASE/g"   \
        -e "s/{{BRIGHT}}/$BRIGHT/g" \
        -e "s/{{DIM}}/$DIM/g"     \
        -e "s/{{BG}}/$BG/g"       \
        -e "s/{{BLACK}}/$BLACK/g" \
        -e "s/{{ERROR}}/$ERROR/g" \
        "$SDDM_THEME_DIR/Main.qml.template" > "$SDDM_THEME_DIR/Main.qml"
    echo "SDDM theme updated. Run 'sudo nixos-rebuild switch' to apply."
fi

# ── 10. Generate .config/nushell/scripts/grave.nu from template ──────────────

sed \
    -e "s/{{BASE}}/$BASE/g"   \
    -e "s/{{BRIGHT}}/$BRIGHT/g" \
    -e "s/{{DIM}}/$DIM/g"     \
    -e "s/{{BG}}/$BG/g"       \
    -e "s/{{BLACK}}/$BLACK/g" \
    "$DOTFILES/.config/nushell/scripts/grave.nu.template" > "$DOTFILES/.config/nushell/scripts/grave.nu"

# ── 11. Generate .config/nvim/lua/config/theme.lua from template ─────────────

NVIM_LUA_DIR="$DOTFILES/.config/nvim/lua/config"
NVIM_TEMPLATE="$NVIM_LUA_DIR/theme.lua.template"
NVIM_CONFIG="$NVIM_LUA_DIR/theme.lua"

mkdir -p "$NVIM_LUA_DIR"

if [ -f "$NVIM_TEMPLATE" ]; then
    sed -e "s/{{BASE}}/$BASE/g" \
        -e "s/{{BRIGHT}}/$BRIGHT/g" \
        -e "s/{{DIM}}/$DIM/g" \
        -e "s/{{SURFACE}}/$SURFACE/g" \
        -e "s/{{BG}}/$BG/g" \
        -e "s/{{BLACK}}/$BLACK/g" \
        -e "s/{{COMMENT}}/$COMMENT/g" \
        -e "s/{{GREEN}}/$GREEN/g" \
        -e "s/{{GREEN_BRIGHT}}/$GREEN_BRIGHT/g" \
        -e "s/{{RED}}/$RED/g" \
        -e "s/{{RED_BRIGHT}}/$RED_BRIGHT/g" \
        -e "s/{{YELLOW}}/$YELLOW/g" \
        -e "s/{{YELLOW_BRIGHT}}/$YELLOW_BRIGHT/g" \
        -e "s/{{BLUE}}/$BLUE/g" \
        -e "s/{{BLUE_BRIGHT}}/$BLUE_BRIGHT/g" \
        -e "s/{{MAGENTA}}/$MAGENTA/g" \
        -e "s/{{MAGENTA_BRIGHT}}/$MAGENTA_BRIGHT/g" \
        -e "s/{{CYAN}}/$CYAN/g" \
        -e "s/{{CYAN_BRIGHT}}/$CYAN_BRIGHT/g" \
        -e "s/{{ERROR}}/$ERROR/g" \
        -e "s/{{ERROR_BRIGHT}}/$ERROR_BRIGHT/g" \
        -e "s/{{WARNING}}/$WARNING/g" \
        -e "s/{{WARNING_BRIGHT}}/$WARNING_BRIGHT/g" \
        -e "s/{{SUCCESS}}/$SUCCESS/g" \
        -e "s/{{SUCCESS_BRIGHT}}/$SUCCESS_BRIGHT/g" \
        -e "s/{{INFO}}/$INFO/g" \
        -e "s/{{INFO_BRIGHT}}/$INFO_BRIGHT/g" \
        "$NVIM_TEMPLATE" > "$NVIM_CONFIG"
    
    # Attempt to reload the theme in all running Neovim instances
    if command -v nvim >/dev/null 2>&1; then
        # Use globbing instead of ls (fixes shellcheck SC2045)
        for server in "${XDG_RUNTIME_DIR:-/run/user/$(id -u)}"/nvim.*.0; do
            # Ensure the file exists (in case the glob doesn't match anything)
            [ -e "$server" ] || continue
            nvim --server "$server" --remote-send '<Esc>:lua package.loaded["config.theme"] = nil<CR>:require("config.theme")<CR>' &>/dev/null
        done
    fi
fi

# ── 12. Generate .config/lazygit/config.yml from template ────────────────────
# lazygit uses ANSI color names that map to terminal palette (set in ghostty)

LAZYGIT_TEMPLATE="$DOTFILES/.config/lazygit/config.yml.template"
LAZYGIT_CONFIG="$DOTFILES/.config/lazygit/config.yml"

if [ -f "$LAZYGIT_TEMPLATE" ]; then
    sed -e "s/{{BASE}}/$BASE/g" \
        -e "s/{{BRIGHT}}/$BRIGHT/g" \
        -e "s/{{DIM}}/$DIM/g" \
        -e "s/{{SURFACE}}/$SURFACE/g" \
        -e "s/{{RED}}/$RED/g" \
        -e "s/{{GREEN}}/$GREEN/g" \
        -e "s/{{YELLOW}}/$YELLOW/g" \
        -e "s/{{BLUE}}/$BLUE/g" \
        -e "s/{{MAGENTA}}/$MAGENTA/g" \
        -e "s/{{CYAN}}/$CYAN/g" \
        "$LAZYGIT_TEMPLATE" > "$LAZYGIT_CONFIG"
fi

echo "Done. Color files generated."
