#!/usr/bin/env bash
# set-theme.sh — Derive a full color palette from one base color and generate
# per-app color files. App configs source/import these files; no hardcoded
# colors live in manually-maintained config files.
#
# Usage:
#   ./scripts/set-theme.sh           # use color from ./theme
#   ./scripts/set-theme.sh '#ff6600' # set new base color and apply

set -euo pipefail

DOTFILES="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
THEME_FILE="$DOTFILES/theme"

# ── 1. Read / update base color ───────────────────────────────────────────────

if [[ -n "${1:-}" ]]; then
    BASE="${1#\#}"
    printf 'base = #%s\n' "$BASE" > "$THEME_FILE"
else
    BASE=$(grep '^base' "$THEME_FILE" | head -1 | sed 's/.*#//' | tr -d '[:space:]')
fi

# ── 2. Derive full palette via Python ─────────────────────────────────────────

eval "$(python3 - "$BASE" <<'PYEOF'
import sys, colorsys

def hex_to_rgb(h):
    h = h.lstrip('#')
    return tuple(int(h[i:i+2], 16) / 255.0 for i in (0, 2, 4))

def rgb_to_hex(r, g, b):
    return '{:02x}{:02x}{:02x}'.format(
        max(0, min(255, round(r * 255))),
        max(0, min(255, round(g * 255))),
        max(0, min(255, round(b * 255))),
    )

def hls_hex(h, l, s):
    r, g, b = colorsys.hls_to_rgb(h, max(0.0, min(1.0, l)), max(0.0, min(1.0, s)))
    return rgb_to_hex(r, g, b)

r, g, b = hex_to_rgb(sys.argv[1])
h, l, s = colorsys.rgb_to_hls(r, g, b)

base         = rgb_to_hex(r, g, b)
bright       = hls_hex(h, min(l * 1.35, 0.92), s)
dim          = hls_hex(h, l * 0.28, s)
bg           = hls_hex(h, l * 0.10, s)
black        = hls_hex(h, l * 0.04, s)

h_err        = (h - 0.06) % 1.0
error        = hls_hex(h_err, l * 0.80, min(s * 1.1, 1.0))
error_bright = hls_hex(h_err, min(l * 1.1, 0.88), min(s * 1.1, 1.0))

l3  = hls_hex(h, l * 0.55, s)
l4  = hls_hex(h, l * 0.75, s)
l5  = hls_hex(h, min(l * 1.50, 0.85), s)
l6  = hls_hex(h, min(l * 1.65, 0.90), s)
l7  = hls_hex(h, min(l * 1.80, 0.95), s)

print(f'BASE={base}')
print(f'BRIGHT={bright}')
print(f'DIM={dim}')
print(f'BG={bg}')
print(f'BLACK={black}')
print(f'ERROR={error}')
print(f'ERROR_BRIGHT={error_bright}')
print(f'P0={black}');  print(f'P1={error}');        print(f'P2={base}');  print(f'P3={l3}')
print(f'P4={dim}');    print(f'P5={base}');          print(f'P6={l4}');    print(f'P7={base}')
print(f'P8={dim}');    print(f'P9={error_bright}');  print(f'P10={l4}');   print(f'P11={l5}')
print(f'P12={base}');  print(f'P13={l5}');           print(f'P14={l6}');   print(f'P15={l7}')
PYEOF
)"

echo "Theme: #$BASE"
echo "  bright=#$BRIGHT  dim=#$DIM  bg=#$BG  black=#$BLACK"

# ── 3. Generate .config/hypr/colors.conf ─────────────────────────────────────

cat > "$DOTFILES/.config/hypr/colors.conf" <<EOF
# Generated by set-theme.sh — do not edit manually.
# Change dotfiles/theme and run scripts/set-theme.sh

\$amber        = rgb($BASE)
\$amber_bright = rgb($BRIGHT)
\$amber_dim    = rgb($DIM)
\$amber_bg     = rgb($BG)
\$black        = rgb($BLACK)
EOF

# ── 4. Generate .config/waybar/colors.css ────────────────────────────────────

cat > "$DOTFILES/.config/waybar/colors.css" <<EOF
/* Generated by set-theme.sh — do not edit manually.
   Change dotfiles/theme and run scripts/set-theme.sh */

@define-color base   #$BASE;
@define-color bright #$BRIGHT;
@define-color dim    #$DIM;
@define-color bg     #$BG;
@define-color black  #$BLACK;
EOF

# ── 5. Generate .config/ghostty/colors.conf ──────────────────────────────────

cat > "$DOTFILES/.config/ghostty/colors.conf" <<EOF
# Generated by set-theme.sh — do not edit manually.
# Change dotfiles/theme and run scripts/set-theme.sh

background           = $BLACK
foreground           = $BASE
cursor-color         = $BASE
selection-background = $DIM
selection-foreground = $BASE
palette = 0=#$P0
palette = 1=#$P1
palette = 2=#$P2
palette = 3=#$P3
palette = 4=#$P4
palette = 5=#$P5
palette = 6=#$P6
palette = 7=#$P7
palette = 8=#$P8
palette = 9=#$P9
palette = 10=#$P10
palette = 11=#$P11
palette = 12=#$P12
palette = 13=#$P13
palette = 14=#$P14
palette = 15=#$P15
EOF

# ── 6. Generate .config/tmux/colors.conf ─────────────────────────────────────

cat > "$DOTFILES/.config/tmux/colors.conf" <<EOF
# Generated by set-theme.sh — do not edit manually.
# Change dotfiles/theme and run scripts/set-theme.sh

set -g status-bg "#$BASE"
set -g status-fg "#$BLACK"
set-option -g pane-border-style fg="#$DIM"
set-option -g pane-active-border-style fg="#$BASE"
EOF

# ── 7. Generate .config/mako/config from template ────────────────────────────

sed \
    -e "s/{{BASE}}/#$BASE/g"   \
    -e "s/{{BRIGHT}}/#$BRIGHT/g" \
    -e "s/{{DIM}}/#$DIM/g"     \
    -e "s/{{BG}}/#$BG/g"       \
    -e "s/{{BLACK}}/#$BLACK/g" \
    "$DOTFILES/.config/mako/config.template" > "$DOTFILES/.config/mako/config"

echo "Done. Color files generated."
